Damasvin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('order.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path

from menu.views import DrinkListView, CoffeeCreateView, BubbleteaCreateView, DrinkUpdateView, DrinkDeleteView

app_name = 'menu'

urlpatterns = [
    path('', DrinkListView.as_view(), name='list'),
    path('add_coffee/', CoffeeCreateView.as_view(), name='add_coffee'),
    path('add_bubbletea/', BubbleteaCreateView.as_view(), name='add_bubbletea'),
    path('update/<int:pk>/', DrinkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', DrinkDeleteView.as_view(), name='delete'),
]

order/urls.py
from django.urls import path

from order import views
from order.views import OrderListView, OrderCreateView, OrderUpdateView, OrderResultView

app_name = 'order'

urlpatterns=[
    path('', OrderListView.as_view(), name='list'),
    path('add/<int:menu_id>/', OrderCreateView.as_view(), name='add'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.order_delete, name='delete'),
    path('result/', OrderResultView.as_view(), name='result'),
    path('pay/', views.pay, name='pay'),
]

menu/models.py
from django.db import models

class Drink(models.Model):
    category = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    price = models.PositiveIntegerField()
    image = models.ImageField(blank=True, upload_to="menu/%Y/%m/%d/")

    def __str__(self):
        return f"카테고리 : {self.category}, 이름: {self.name}, 가격: {self.price}"

class Coffee(Drink):
    pass

class Bubbletea(Drink):
    pass

order/models.py
from django.db import models

from menu.models import Drink


class Order(models.Model):
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE, related_name='order')
    price = models.PositiveIntegerField()
    stock = models.PositiveIntegerField(default=1)
    cup = models.IntegerField(default=0) #0:레귤러/1:점보
    ice = models.IntegerField(default=100) #0, 50, 100, 150
    suger = models.IntegerField(default=100) #0, 50, 100, 150
    pearl = models.CharField(max_length=10, default="타피오카")


    def __str__(self):
        _CUPS = ['레귤러', '점보']
        result = f'음료: {self.drink.name}, 가격: {self.price}, 개수: {self.stock},' \
                 f'컵: {_CUPS[self.cup]}, 얼음량: {self.ice}%, 당도: {self.suger}%'
        if self.drink.category == 'Bubbletea':
            result += f', 펄: {self.pearl}'
        return result

order/forms.py
from django import forms

from order.models import Order


class OrderModelForm(forms.ModelForm):
    _CUPS = (('0', '레귤러'), ('1', '점보'))
    _ICES = (('0', '0%'), ('50', '50%'), ('100', '100%'), ('150', '150%'))
    _SUGARS = (('0', '0%'), ('50', '50%'), ('100', '100%'), ('150', '150%'))
    _PEALRS = (('타피오카', '타피오카'), ('코코', '코코'), ('젤리', '젤리'), ('알로에', '알로에'))
    cup = forms.ChoiceField(widget=forms.Select, choices=_CUPS, initial=0)
    ice = forms.ChoiceField(widget=forms.RadioSelect, choices=_ICES, initial=100)
    suger = forms.ChoiceField(widget=forms.RadioSelect, choices=_SUGARS, initial=100)
    pearl = forms.ChoiceField(widget=forms.RadioSelect, choices=_PEALRS, initial='타피오카')

    class Meta:
        model = Order
        fields = ['drink', 'cup', 'ice', 'suger', 'pearl', 'stock', 'price']

menu/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from menu.models import Drink, Coffee, Bubbletea


class DrinkListView(ListView):
    model = Drink
    # paginate_by = 3


class CoffeeCreateView(CreateView):
    model = Coffee
    fields = '__all__'
    template_name = 'menu/drink_create.html'
    success_url = reverse_lazy('menu:list')
    initial = {'category':'Coffee'}

class BubbleteaCreateView(CreateView):
    model = Bubbletea
    fields = '__all__'
    template_name = 'menu/drink_create.html'
    success_url = reverse_lazy('menu:list')
    initial = {'category': 'Bubbletea'}

class DrinkUpdateView(UpdateView):
    model = Drink
    fields = '__all__'
    template_name_su = 'menu/drink_update.html'
    success_url = reverse_lazy('menu:list')

class DrinkDeleteView(DeleteView):
    model = Drink
    success_url = reverse_lazy('menu:list')

order/views.py
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView

from menu.models import Drink
from order.forms import OrderModelForm
from order.models import Order


class OrderListView(ListView):
    model = Order

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_list'] = Drink.objects.all()
        context['total_price'] = Order.objects.all().aggregate(total_price=Sum('price')).get('total_price', 0)
        return context

class OrderCreateView(CreateView):
    model = Order
    # fields = '__all__'
    form_class = OrderModelForm
    template_name_suffix = '_create'
    success_url = reverse_lazy('order:list')

    def get_initial(self):
        initial = super().get_initial()
        initial['drink'] = self.kwargs.get('menu_id')
        initial['price'] = Drink.objects.get(id=self.kwargs.get('menu_id')).price
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['drink_price'] = Drink.objects.get(id=self.kwargs['menu_id']).price
        return context

class OrderUpdateView(UpdateView):
    model = Order
    # fields = '__all__'
    form_class = OrderModelForm
    template_name_suffix = '_update'
    success_url = reverse_lazy('order:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['drink_price'] = Order.objects.get(id=self.kwargs['pk']).drink.price
        return context

def order_delete(request, pk):
    order = Order.objects.get(id=pk)
    order.delete()
    return redirect('order:list')

class OrderResultView(ListView):
    model = Order
    template_name_suffix = '_result'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_price'] = Order.objects.all().aggregate(total_price=Sum('price')).get('total_price', 0)
        return context

def pay(request):
    orders = Order.objects.all()
    orders.delete()
    return redirect('order:list')

menu/templates/menu/bubbletea_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bubbletea Add</title>
</head>
<body>

</body>
</html>

menu/templates/menu/drink_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>Drink Confrim Delete</title>
</head>
<body class="container">
    <h1>삭제하시겠습니까?</h1>
    <h5>{{ drink }}</h5>
    {% if drink.image != '' %}
    <img src="{{ drink.image.url }}" alt="" style="height:200px" class="img-rounded mx-auto d-block">
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
        <button type="button" class="btn btn-primary btn-sm" onclick="history.back(-1)">Cancle</button>
    </form>
</body>
</html>

menu/templates/menu/drink_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>Drink Add</title>
</head>
<body class="container">
<h1>Drink Add</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger btn-sm">Add</button>
    <button type="button" class="btn btn-primary btn-sm" onclick="history.back(-1)">Cancle</button>
</form>
</body>
</html>

menu/templates/menu/drink_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>Drink List</title>
</head>
<body class="container">
<h1>Cafe menu</h1>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>#</th>
        <th>image</th>
        <th>Drink</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tboby>
        {% for drink in drink_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            {%  if drink.image != '' %}
            <td><img src="{{ drink.image.url }}" alt="아메리카노" width="100" class="img-rounded mx-auto d-block"></td>
            {% else %}
            <td>------</td>
            {% endif %}
            <td>{{ drink }}</td>
            <td><a href="{% url 'menu:update' pk=drink.id %}">Modify</a></td>
            <td><a href="{% url 'menu:delete' pk=drink.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tboby>
</table>
<a href="{% url 'menu:add_coffee' %}" class="btn btn-primary">Add Coffee</a>
<a href="{% url 'menu:add_bubbletea' %}" class="btn btn-primary">Add Bubbletea</a>
</body>
</html>

menu/templates/menu/drink_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>Drink Update</title>
</head>
<body class="container">
<h1>Drink Update</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger btn-sm">modify</button>
    <button type="button" class="btn btn-primary btn-sm" onclick="history.back(-1)">Cancle</button>
</form>
</body>
</html>

order/templates/order/order_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Add</title>
    <script>
        window.onload = function () {
            let drink_price = {{ drink_price }}
            let stock = document.querySelector('#id_stock')
            let cup = document.querySelector('#id_cup')
            let price = document.querySelector('#id_price')
            stock.addEventListener('change', () => setPrice())
            cup.addEventListener('change', () => setPrice())

            function setPrice() {
                let total_price = drink_price * stock.value
                if (cup.value == 1){
                    total_price += 500 * stock.value
                }
                price.value = total_price
            }
        }
    </script>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
    <button type="button" onclick="history.back()">Cancel</button>
</form>
</body>
</html>

order/templates/order/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>Order List</title>
    <style>
        .button_result {
            width: 100%;
            background-color:gold; /* Green */
            border: none;
            color: black;
            padding: 20px 0px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            transition-duration: 0.4s;
            box-shadow: 0 0 8px 0 rgba(0, 0, 0, 0.4);
        }
        .button_result:hover {
            box-shadow: 0 0 0 0;
            transform: translateY(2px);
        }

    </style>
</head>
<body class="container">

<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Order</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for order in order_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ order }}</td>
            <td><a href="{% url 'order:update' pk=order.id %}">Modify</a></td>
            <td><a href="{% url 'order:delete' pk=order.id %}">Delete</a></td>
        </tr>
    {% endfor %}
    {% if total_price != None %}
    <tr>
        <td colspan="2" class="bg-success text-right">총 금 액 : </td>
        <td class="bg-success">{{ total_price }}</td>
        <td><a href="{% url 'order:result' %}" class="btn btn-sm btn-warning">계산하기</a></td>
    </tr>
    {% endif %}
    </tbody>
</table>
<h2>Menu</h2>
    <div class="row">
    <div class="card-columns">
{% for menu in menu_list %}
    <div class="card">
        <img class="card-img-top mx-auto d-block" src="{{ menu.image.url }}" width="100" height="300">
        <div class="card-body">
            <h5 class="card-title text-center">{{ menu.name }}</h5>
            <p class="card-text text-center">{{ menu.price }}원</p>
            <a href="{% url 'order:add' menu_id=menu.id %}" class="btn btn-primary stretched-link mx-auto d-block">주문하기</a>
        </div>
    </div>
{% endfor %}
    </div>
    </div>
</body>
</html>

order/templates/order/order_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Result</title>
</head>
<body>
<table>
    <thead>
    <tr>
        <th>#</th>
        <th>image</th>
        <th>Drink</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for order in order_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ order }}</td>
            <td><a href="{% url 'order:update' pk=order.id %}">Modify</a></td>
            <td><a href="{% url 'order:delete' pk=order.id %}">Delete</a></td>
        </tr>
    {% endfor %}
    {% if total_price != None %}
        <tr>
            <td colspan="2" style="background-color: darkseagreen">총 금 액</td>
            <td colspan="2" style="background-color: darkseagreen">{{ total_price }}</td>
        </tr>
    {% endif %}
    <tr>
        <td colspan="2"><a href="{% url 'order:pay' %}">지불하기</a></td>
        <td colspan="2"><button type="button" onclick="history.back()">Cancel</button></td>
    </tr>
    </tbody>
</table>
</body>
</html>

order/templates/order/order_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Oreder Modify</title>
    <script>
        window.onload = function () {
            let drink_price = {{ drink_price }}
            let stock = document.querySelector('#id_stock')
            let cup = document.querySelector('#id_cup')
            let price = document.querySelector('#id_price')
            stock.addEventListener('change', () => setPrice())
            cup.addEventListener('change', () => setPrice())

            function setPrice() {
                let total_price = drink_price * stock.value
                if (cup.value == 1){
                    total_price += 500 * stock.value
                }
                price.value = total_price
            }
        }
    </script>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Modify</button>
    <button type="submit" onclick="history.back()">Cancel</button>
</form>
</body>
</html>